name: Audit GitHub Workflows
on:
  push:
  schedule:
    - cron: '0 0 * * 0' # 12:00am on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup-python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 #v5.4.0
        with:
          python-version: '3.13.2'
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          python -m pipx ensurepath
      - name: Install ghwfauditor
        run: |
          pipx install 'git+https://github.com/Xenorf/gh-workflow-auditor.git@ef8404fb9bafea418b5768b6475416f3128fd9a7'
      - name: ghwfauditor
        env:
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'info' }}
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          ghwfauditor --type user enzowritescode --log-level $LOG_LEVEL

          # Check if the log file has any content
          if [[ "$LOG_LEVEL" =~ ^(warning|error|critical)$ ]] && [ -s "scan.log" ]; then
            echo "Issues were found! Failing the workflow."
            exit 1
          else
            echo "No findings. Success"
          fi
