name: Audit GitHub Workflows
on: push
  # push:
  # schedule:
  #   - cron: '*/15 * * * *' # every 15 min -- 0 0 * * 0 # 12:00am on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: TinderSec/gh-workflow-auditor
          ref: 72dba22745255152c6ff73ad454792ef8700fa36
      - name: setup-python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d #v5.1.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: gh-workflow-auditor
        env:
          PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python3 main.py --type user enzowritescode --log-level warning

