name: Audit GitHub Workflows
on: push
  # push:
  # schedule:
  #   - cron: '*/15 * * * *' # every 15 min -- 0 0 * * 0 # 12:00am on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 #v5.4.0
        with:
          python-version: '3.14'
          cache: 'pip'
      - name: Install pipx
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          python -m pipx ensurepath
      - name: Install ghwfauditor
        run: |
          pipx install 'git+https://github.com/Xenorf/gh-workflow-auditor.git'
      - name: gh-workflow-auditor
        run: |
          ghwfauditor --type user enzowritescode --log-level debug

